name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]

env:
  KUBE_URL: ${{ secrets.KUBE_URL }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
  DOCKERHUBPAS: ${{ secrets.DOCKERHUBPAS }}


jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: Build the stack
        run: docker-compose build
      
      - name: Push the stack
        run: |
          docker login -u csdevcore -p $DOCKERHUBPAS
          docker-compose push

      - name: k8s deploy
        run: |
          kubectl config set-cluster lab4-klaster --server="$KUBE_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=lab4-klaster --user=admin
          kubectl config use-context default
          kubectl apply -f k8s.yaml
          kubectl port-forward gateway-5f7f94b9dd-f8lq6 8080:80

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"